# Generated by Django 2.2.3 on 2019-07-23 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
                ('address', models.CharField(default='', max_length=512, verbose_name='Адрес')),
                ('ns_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код NS2000')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.PositiveIntegerField(verbose_name='Номер графика')),
                ('reis', models.PositiveIntegerField(verbose_name='Номер рейса')),
                ('reis_start', models.PositiveIntegerField(verbose_name='Выезд со склада (в секундах с полуночи)')),
                ('store_return_distance', models.PositiveIntegerField(default=0, verbose_name='Расстояние от последней точки до склада (в метрах)')),
                ('store_return_time', models.PositiveIntegerField(default=0, verbose_name='Время возврата на склад от последней точки (в секундах)')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RouteDot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='Номер по порядку в маршруте')),
                ('time_in', models.PositiveIntegerField(verbose_name='Заезд в ТТ(в секундах с полуночи)')),
                ('time_out', models.PositiveIntegerField(verbose_name='Выезд из ТТ(в секундах с полуночи)')),
                ('wait_time', models.PositiveIntegerField(verbose_name='Время ожидания до окна приемки ТТ (в секундах)')),
                ('distance', models.PositiveIntegerField(verbose_name='Расстояние от предыдущей точки маршрута до этой (в метрах)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрутов',
            },
        ),
        migrations.CreateModel(
            name='RouteSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('username', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расчет маршрутов',
                'verbose_name_plural': 'Расчеты маршрутов',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
                ('address', models.CharField(default='', max_length=512, verbose_name='Адрес')),
                ('ns_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код NS2000')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='RouteStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_bad', models.PositiveIntegerField(verbose_name='Нераспределенных приоритетных точек')),
                ('regular_bad', models.PositiveIntegerField(verbose_name='Нераспределенных обычных точек')),
                ('auto_count', models.PositiveIntegerField(verbose_name='Автомобилей использовано')),
                ('reis_count', models.PositiveIntegerField(verbose_name='Рейсов использовано')),
                ('costs', models.PositiveIntegerField(verbose_name='Общие временные затраты (в секундах)')),
                ('with_return', models.BooleanField(default=False, verbose_name='Расчет с возвратом на склад')),
                ('route_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.RouteSet', verbose_name='Расчет')),
            ],
            options={
                'verbose_name': 'Статистика расчета',
                'verbose_name_plural': 'Статистика расчетов',
            },
        ),
        migrations.CreateModel(
            name='RouteInitDot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256, verbose_name='Название торговой точки')),
                ('quantity', models.FloatField(verbose_name='Заказанное кол-во')),
                ('window_in', models.PositiveIntegerField(verbose_name='Окно приемки в ТТ с (в секундах с полуночи)')),
                ('window_out', models.PositiveIntegerField(verbose_name='Окно приемки в ТТ по (в секундах с полуночи)')),
                ('process_time', models.PositiveIntegerField(verbose_name='Длительность выгрузки в ТТ (в секундах)')),
                ('priority', models.PositiveIntegerField(verbose_name='Приоритет ТТ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client', verbose_name='Торговая точка')),
                ('route_dot', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RouteDot', verbose_name='Точка маршрута')),
                ('route_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RouteSet', verbose_name='Расчет')),
            ],
            options={
                'verbose_name': 'Исходная точка маршрута',
                'verbose_name_plural': 'Исходные точки маршрутов',
            },
        ),
        migrations.CreateModel(
            name='RouteInitAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='Порядковый номер (График)')),
                ('name', models.CharField(max_length=50, verbose_name='Гос.Номер')),
                ('capacity', models.FloatField(verbose_name='Емкость авто (лот.)')),
                ('reis_max', models.PositiveIntegerField(verbose_name='Максимальное количество рейсов')),
                ('reis_start', models.PositiveIntegerField(verbose_name='Выезд со склада (в секундах с полуночи)')),
                ('route_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RouteSet', verbose_name='Расчет')),
            ],
            options={
                'verbose_name': 'Исходный авто',
                'verbose_name_plural': 'Исходные авто',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='route_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RouteSet', verbose_name='Расчет'),
        ),
        migrations.AddField(
            model_name='route',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Store', verbose_name='Склад'),
        ),
        migrations.AddIndex(
            model_name='routeset',
            index=models.Index(fields=['username', '-id'], name='main_routes_usernam_e01e71_idx'),
        ),
        migrations.AddIndex(
            model_name='routeinitauto',
            index=models.Index(fields=['route_set', 'num'], name='main_routei_route_s_c772ea_idx'),
        ),
        migrations.AddIndex(
            model_name='routedot',
            index=models.Index(fields=['route', 'num'], name='main_routed_route_i_5a867c_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_set', 'graph', 'reis'], name='main_route_route_s_169858_idx'),
        ),
    ]
