# Generated by Django 2.2.3 on 2019-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190724_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinitauto',
            name='driver_limit',
            field=models.PositiveIntegerField(default=86400, verbose_name='Ограничение смены водителя (в секундах)'),
        ),
    ]
