# Generated by Django 2.2.3 on 2019-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_routeinitauto_driver_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='load_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Время погрузки (в секундах)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='reis_start',
            field=models.PositiveIntegerField(verbose_name='Приезд на погрузку (в секундах с полуночи)'),
        ),
        migrations.AlterField(
            model_name='routeinitauto',
            name='reis_start',
            field=models.PositiveIntegerField(verbose_name='Время начала работы водителя (в секундах с полуночи)'),
        ),
    ]
