# Generated by Django 2.2.4 on 2019-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190801_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestat',
            name='high_accuracy',
            field=models.BooleanField(default=False, verbose_name='Высокая точность расчета'),
        ),
    ]
