# Generated by Django 2.2.4 on 2019-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_routestat_high_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinitauto',
            name='reis_start_free',
            field=models.BooleanField(default=False, verbose_name='Время начала работы водителя не задано'),
        ),
    ]
