# Generated by Django 2.2.4 on 2019-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_routeinitauto_reis_start_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestat',
            name='dyn_auto_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Дин.авто: Емкость'),
        ),
        migrations.AddField(
            model_name='routestat',
            name='dyn_auto_count_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Дин.авто: Макс кол-во дин. авто'),
        ),
        migrations.AddField(
            model_name='routestat',
            name='dyn_auto_driver_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Дин.авто: Ограничение смены водителя'),
        ),
        migrations.AddField(
            model_name='routestat',
            name='dyn_auto_reis_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Дин.авто: Макс кол-во рейсов'),
        ),
    ]
