# Generated by Django 2.2.4 on 2019-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_route_dyn_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestat',
            name='auto_min',
            field=models.BooleanField(default=False, verbose_name='Режим минимизации кол-ва авто'),
        ),
    ]
