# Generated by Django 2.2.4 on 2019-11-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191101_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinitdot',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Client', verbose_name='Торговая точка'),
        ),
    ]
