# Generated by Django 2.2.4 on 2020-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200217_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinitdot',
            name='client_address',
            field=models.TextField(default=None, null=True, verbose_name='Адрес торговой точки'),
        ),
    ]
